language: node_js
sudo: false
node_js:
  - node
before_install:
  - npm i -g npm@5.8.0
install:
  - npm ci
script:
  - npm run lint
  - npm test
deploy:
  provider: npm
  email: "CalebLemoine@gmail.com"
  api_key: $npmToken