sudo: false
language: node_js
node_js:
  - node
install:
  - npm ci
script:
  - npm run lint
  - npm test
after_script:
  - npm run coverage
deploy:
  on:
      branch: master
  provider: npm
  email: CalebLemoine@gmail.com
  api_key: $npmToken